[project]
name = "intersystems_pyprod"
version = "1.0.0b2"
authors = [
  { name="Geet Kalra", email="geet.kalra@intersystems.com" },
]


[project.scripts]
intersystems_pyprod = "intersystems_pyprod._parser:main"
